### ISSUE TITLE
[Update Required] Bump mod to 1.12.2

### ISSUE THREAD

**Issue by tompointexe** [SetCr4/EmoteRain#2]
Hi will this mod be updated to 1.12.2 beatsaber ?
Thanks

**Comment by SetCr4** [comment]
Hey there Tom,
yes the mod will be updated, however neither ChatCore nor ESCv3 have been updated yet. 
I will test their old versions later today and bumping EmoteRain, if there are no other issues.

**Comment by tompointexe** [comment]
Yeah i know but a friend updated chatcore and made a better enchansed stream chat :) i can give you the discord link to acces the plugin if you want while waiting for the official chatcore / ESCV3 releases

**Comment by SetCr4** [comment]
Yeah why not. I'll look how much changed.

**Comment by tompointexe** [comment]
https://discord.gg/K4X94Ea :)
You just need to take the role "Beta testing" in #role-assignement :)
